// This file is generated by rust-protobuf 2.24.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `proto/keyprovider.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_24_1;

#[derive(PartialEq,Clone,Default)]
pub struct keyProviderKeyWrapProtocolInput {
    // message fields
    pub KeyProviderKeyWrapProtocolInput: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a keyProviderKeyWrapProtocolInput {
    fn default() -> &'a keyProviderKeyWrapProtocolInput {
        <keyProviderKeyWrapProtocolInput as ::protobuf::Message>::default_instance()
    }
}

impl keyProviderKeyWrapProtocolInput {
    pub fn new() -> keyProviderKeyWrapProtocolInput {
        ::std::default::Default::default()
    }

    // bytes KeyProviderKeyWrapProtocolInput = 1;


    pub fn get_KeyProviderKeyWrapProtocolInput(&self) -> &[u8] {
        &self.KeyProviderKeyWrapProtocolInput
    }
    pub fn clear_KeyProviderKeyWrapProtocolInput(&mut self) {
        self.KeyProviderKeyWrapProtocolInput.clear();
    }

    // Param is passed by value, moved
    pub fn set_KeyProviderKeyWrapProtocolInput(&mut self, v: ::std::vec::Vec<u8>) {
        self.KeyProviderKeyWrapProtocolInput = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_KeyProviderKeyWrapProtocolInput(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.KeyProviderKeyWrapProtocolInput
    }

    // Take field
    pub fn take_KeyProviderKeyWrapProtocolInput(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.KeyProviderKeyWrapProtocolInput, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for keyProviderKeyWrapProtocolInput {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.KeyProviderKeyWrapProtocolInput)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.KeyProviderKeyWrapProtocolInput.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.KeyProviderKeyWrapProtocolInput);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.KeyProviderKeyWrapProtocolInput.is_empty() {
            os.write_bytes(1, &self.KeyProviderKeyWrapProtocolInput)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> keyProviderKeyWrapProtocolInput {
        keyProviderKeyWrapProtocolInput::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "KeyProviderKeyWrapProtocolInput",
                |m: &keyProviderKeyWrapProtocolInput| { &m.KeyProviderKeyWrapProtocolInput },
                |m: &mut keyProviderKeyWrapProtocolInput| { &mut m.KeyProviderKeyWrapProtocolInput },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<keyProviderKeyWrapProtocolInput>(
                "keyProviderKeyWrapProtocolInput",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static keyProviderKeyWrapProtocolInput {
        static instance: ::protobuf::rt::LazyV2<keyProviderKeyWrapProtocolInput> = ::protobuf::rt::LazyV2::INIT;
        instance.get(keyProviderKeyWrapProtocolInput::new)
    }
}

impl ::protobuf::Clear for keyProviderKeyWrapProtocolInput {
    fn clear(&mut self) {
        self.KeyProviderKeyWrapProtocolInput.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for keyProviderKeyWrapProtocolInput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for keyProviderKeyWrapProtocolInput {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct keyProviderKeyWrapProtocolOutput {
    // message fields
    pub KeyProviderKeyWrapProtocolOutput: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a keyProviderKeyWrapProtocolOutput {
    fn default() -> &'a keyProviderKeyWrapProtocolOutput {
        <keyProviderKeyWrapProtocolOutput as ::protobuf::Message>::default_instance()
    }
}

impl keyProviderKeyWrapProtocolOutput {
    pub fn new() -> keyProviderKeyWrapProtocolOutput {
        ::std::default::Default::default()
    }

    // bytes KeyProviderKeyWrapProtocolOutput = 1;


    pub fn get_KeyProviderKeyWrapProtocolOutput(&self) -> &[u8] {
        &self.KeyProviderKeyWrapProtocolOutput
    }
    pub fn clear_KeyProviderKeyWrapProtocolOutput(&mut self) {
        self.KeyProviderKeyWrapProtocolOutput.clear();
    }

    // Param is passed by value, moved
    pub fn set_KeyProviderKeyWrapProtocolOutput(&mut self, v: ::std::vec::Vec<u8>) {
        self.KeyProviderKeyWrapProtocolOutput = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_KeyProviderKeyWrapProtocolOutput(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.KeyProviderKeyWrapProtocolOutput
    }

    // Take field
    pub fn take_KeyProviderKeyWrapProtocolOutput(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.KeyProviderKeyWrapProtocolOutput, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for keyProviderKeyWrapProtocolOutput {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.KeyProviderKeyWrapProtocolOutput)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.KeyProviderKeyWrapProtocolOutput.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.KeyProviderKeyWrapProtocolOutput);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.KeyProviderKeyWrapProtocolOutput.is_empty() {
            os.write_bytes(1, &self.KeyProviderKeyWrapProtocolOutput)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> keyProviderKeyWrapProtocolOutput {
        keyProviderKeyWrapProtocolOutput::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "KeyProviderKeyWrapProtocolOutput",
                |m: &keyProviderKeyWrapProtocolOutput| { &m.KeyProviderKeyWrapProtocolOutput },
                |m: &mut keyProviderKeyWrapProtocolOutput| { &mut m.KeyProviderKeyWrapProtocolOutput },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<keyProviderKeyWrapProtocolOutput>(
                "keyProviderKeyWrapProtocolOutput",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static keyProviderKeyWrapProtocolOutput {
        static instance: ::protobuf::rt::LazyV2<keyProviderKeyWrapProtocolOutput> = ::protobuf::rt::LazyV2::INIT;
        instance.get(keyProviderKeyWrapProtocolOutput::new)
    }
}

impl ::protobuf::Clear for keyProviderKeyWrapProtocolOutput {
    fn clear(&mut self) {
        self.KeyProviderKeyWrapProtocolOutput.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for keyProviderKeyWrapProtocolOutput {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for keyProviderKeyWrapProtocolOutput {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x17proto/keyprovider.proto\x12\x0bkeyprovider\"k\n\x1fkeyProviderKeyW\
    rapProtocolInput\x12H\n\x1fKeyProviderKeyWrapProtocolInput\x18\x01\x20\
    \x01(\x0cR\x1fKeyProviderKeyWrapProtocolInput\"n\n\x20keyProviderKeyWrap\
    ProtocolOutput\x12J\n\x20KeyProviderKeyWrapProtocolOutput\x18\x01\x20\
    \x01(\x0cR\x20KeyProviderKeyWrapProtocolOutput2\x80\x01\n\x12KeyProvider\
    Service\x12j\n\tUnWrapKey\x12,.keyprovider.keyProviderKeyWrapProtocolInp\
    ut\x1a-.keyprovider.keyProviderKeyWrapProtocolOutput\"\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
