[package]
name = "attestation_agent"
version = "0.1.0"
authors = ["The Attestation Agent Authors"]
publish = false
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
aes-gcm = "0.10.1"
base64 = "0.13.0"
anyhow = "1.0"
log = "0.4.14"
env_logger = "0.9.0"
foreign-types = "0.5.0"
openssl = { version = "0.10", optional = true, features = ["vendored"]}
strum = { version = "0.24.0", features = ["derive"] }
rsa = "0.6.1"
sha2 = "0.10"
rand = "0.8.5"
async-trait = "0.1.56"
tonic = { version = "0.8.0", optional = true }
prost = { version = "0.11.0", optional = true }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"], optional = true }
uuid = { version = "1.1.2", features = ["serde", "v4"], optional = true }
bincode = { version = "1.3.3", optional = true }
futures-util = "0.3.21"

[dev-dependencies]
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.8.0"
shadow-rs = "0.16.1"

[features]
default = ["sample_kbc"]
sample_kbc = []
cc_kbc = []
eaa_kbc = []
offline_fs_kbc = ["openssl"]
offline_sev_kbc = ["openssl"]
online_sev_kbc = ["openssl", "tonic", "prost", "uuid", "bincode", "tokio"]
