[package]
name = "attestation_agent"
version = "0.1.0"
authors = ["The Attestation Agent Authors"]
publish = false
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.1", optional = true }
anyhow = "1.0"
async-trait = "0.1.56"
base64 = "0.13.0"
bincode = { version = "1.3.3", optional = true }
ctr = { version = "0.9.2", optional = true }
foreign-types = { version = "0.5.0", optional = true }
kbs-types = { git = "https://github.com/virtee/kbs-types" }
log = "0.4.14"
openssl = { version = "0.10", features = ["vendored"], optional = true}
prost = { version = "0.11.0", optional = true }
rand = { version = "0.8.5", optional = true }
reqwest = { version = "0.11.13", features = ["cookies", "json"], optional = true }
rsa = { version = "0.6.1", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = { version = "0.10", optional = true }
strum = { version = "0.24.0", features = ["derive"] }
tdx-attest-rs = { git = "https://github.com/intel/SGXDataCenterAttestationPrimitives", rev = "85cf8bdd", optional = true }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"], optional = true }
tonic = { version = "0.8.0", optional = true }
url = "2.3.1"
uuid = { version = "1.1.2", features = ["serde", "v4"], optional = true }
zeroize = "1.5.7"

[dev-dependencies]
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = { version = "0.8.0", optional = true }

[features]
default = ["sample_kbc", "rust-crypto"]
sample_kbc = []
cc_kbc = ["rand", "rsa", "sha2", "tdx-attest-rs", "reqwest"]
eaa_kbc = ["foreign-types"]
offline_fs_kbc = []
offline_sev_kbc = []
online_sev_kbc = ["tonic", "prost", "uuid", "bincode", "tokio"]
gen-proto = ["tonic-build"]

# Either `rust-crypto` or `openssl` should be enabled to work as underlying crypto module
rust-crypto = ["dep:aes-gcm", "ctr"]
openssl = ["dep:openssl"]
