[package]
name = "attestation-agent"
version = "0.1.0"
authors = ["The Attestation Agent Authors"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.56"
attestation_agent = { path = "../", default-features = false }
base64 = "0.13.0"
clap = "3.2.5"
env_logger = "0.9.0"
futures = "0.3.5"
lazy_static = "1.4.0"
log = "0.4.14"
prost = { version = "0.10.4", optional = true }
protobuf = { version = "3.1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread"], optional = true }
tonic = { version = "0.7.2", optional = true }
ttrpc = { version = "0.7.1", optional = true }

[build-dependencies]
tonic-build = { version = "0.7.2", optional = true }
ttrpc-codegen = { version = "0.4.1", optional = true }

[features]
default = ["sample_kbc", "grpc", "ttrpc"]
grpc = ["tokio", "tonic", "prost", "tonic-build"]
ttrpc = ["dep:ttrpc", "ttrpc-codegen", "protobuf"]
sample_kbc = ["attestation_agent/sample_kbc"]
cc_kbc = ["attestation_agent/cc_kbc"]
eaa_kbc = ["attestation_agent/eaa_kbc"]
offline_fs_kbc = ["attestation_agent/offline_fs_kbc"]
offline_sev_kbc = ["attestation_agent/offline_sev_kbc"]
online_sev_kbc = ["attestation_agent/online_sev_kbc"]
openssl = ["attestation_agent/openssl"]
rust-crypto = ["attestation_agent/rust-crypto"]