[package]
name = "crypto"
version = "0.1.0"
authors = ["The Attestation Agent Authors"]
publish = false
edition = "2021"

[dependencies]
aes-gcm = { version = "0.10.1", optional = true }
anyhow.workspace = true
base64.workspace = true
kbs-types.workspace = true
rsa = { version = "0.6.1" }
openssl = { version = "0.10", features = ["vendored"], optional = true}
ctr = { version = "0.9.2", optional = true }
zeroize.workspace = true
strum.workspace = true
rand = { version = "0.8.5" }
sha2 = { version = "0.10" }

[features]
default = ["rust-crypto"]
rust-crypto = ["dep:aes-gcm", "ctr"]
openssl = ["dep:openssl"]