name: CC kbc build CI
on:
  push:
    paths:
      - 'src/kbc_modules/cc_kbc/**'
      - '.github/workflows/cc_kbc.yml'
  pull_request:
    paths:
      - 'src/kbc_modules/cc_kbc/**'
      - '.github/workflows/cc_kbc.yml'
  create:
    paths:
      - 'src/kbc_modules/cc_kbc/**'

jobs:
  cc_kbc_ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable

    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt

      - name: Install TDX dependencies
        run: |
          sudo curl -L https://download.01.org/intel-sgx/sgx_repo/ubuntu/intel-sgx-deb.key | sudo apt-key add -
          sudo echo 'deb [arch=amd64] https://download.01.org/intel-sgx/sgx_repo/ubuntu focal main' | sudo tee /etc/apt/sources.list.d/intel-sgx.list
          sudo apt-get update
          sudo apt-get install -y libtdx-attest-dev

      - name: Build and install with cc_kbc feature
        run: |
          make KBC=cc_kbc && make install

      - name: Run rust lint check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          # We are getting error in generated code due to derive_partial_eq_without_eq check, so ignore it for now
          args: --all-targets --features cc_kbc,rust-crypto -- -D warnings -A clippy::derive_partial_eq_without_eq