name: EAA kbc build CI
on:
  push:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'
      - '.github/workflows/eaa_kbc.yml'
  pull_request:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'
      - '.github/workflows/eaa_kbc.yml'
  create:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'

jobs:
  eaa_kbc_ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable

    container: runetest/compilation-testing:ubuntu18.04
          
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain
        run: |
          apt-get update && apt-get install -y cargo
          cp -r /root/.cargo /github/home/.cargo
          rustup install stable
          rustup default stable

      - name: Build and install rats-tls
        run: | 
          apt-get install -y libcurl4-openssl-dev
          git clone https://github.com/inclavare-containers/rats-tls
          cd rats-tls
          git reset --hard 5de6fc308f2a18f4105429451c85e6173b42ab9d
          cmake -DBUILD_SAMPLES=on -H. -Bbuild
          make -C build install
      
      - name: Build AA with EAA KBC
        run: |
          make KBC=eaa_kbc && make install

      - name: Run cargo test with eaa_kbc feature
        run: |
          RUSTFLAGS="-C link-args=-Wl,-rpath,/usr/local/lib/rats-tls" cargo test --features eaa_kbc kbc_modules::eaa_kbc