name: EAA kbc build CI
on:
  push:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'
  pull_request:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'
  create:
    paths:
      - 'src/kbc_modules/eaa_kbc/**'

jobs:
  eaa_kbc_ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - nightly
          
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up docker
        uses: docker-practice/actions-setup-docker@master

      - name: Install Rust toolchain (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt

      - name: Create rats-tls compiling container
        run: |
          rats_compile_env=$(docker run -itd --privileged --rm --net host -v /usr/local/lib:/usr/local/lib inclavarecontainers/test:compile-check-ubuntu18.04);
          echo "rats_compile_env=$rats_compile_env" >> $GITHUB_ENV

      - name: Build and install rats-tls
        run: | 
          docker exec $rats_compile_env bash -c 'git clone https://github.com/alibaba/inclavare-containers;
          cd inclavare-containers/rats-tls;
          cmake -DBUILD_SAMPLES=on -H. -Bbuild;
          make -C build install'
      
      - name: Stop rats-tls compiling container
        run: |
          docker stop $rats_compile_env
      
      - name: Build AA with EAA KBC
        run: |
          make KBC=eaa_kbc && make install