name: KMS CI
on:
  push:
    paths:
      - 'deps/kms/**'
      - '.github/workflows/kms.yml'
  pull_request:
    paths:
      - 'deps/kms/**'
      - '.github/workflows/kms.yml'
  create:
    paths:
      - 'deps/kms/**'
      - '.github/workflows/kms.yml'

jobs:
  crypto_ci:
    if: github.event_name == 'pull_request'
    name: Check
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Rust toolchain (stable)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run rust fmt check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -p kms -- --check

      - name: Run rust lint check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p kms --all-features
      
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p kms --all-features
